### PR TITLE
add strictInterfaceWithOptionals combinator to tests

### PR DESCRIPTION
**Pull request by gcanti**
..to prevent regressions. /cc @gunzip

### CODE REVIEW

**Comment by gunzip** [comment]
a question, why not

```
): t.Type<
  t.TypeOfProps<R> & t.TypeOfPartialProps<O>,
  t.OutputOfProps<R> & t.OutputOfPartialProps<O>
> {

```

?

**Comment by gcanti** [comment]
because the extracted type would be less readable

```ts
const T = strictInterfaceWithOptionals({ foo: t.string }, { bar: t.string }, 'T')

type TT = t.TypeOf<typeof T>
/*
type TT = {
    foo: string;
} & {
    bar?: string | undefined;
}
*/
```

versus

```ts
/*
type TT = t.TypeOfProps<{
    foo: t.StringType;
}> & t.TypeOfPartialProps<{
    bar: t.StringType;
}>
*/
```

**Comment by gcanti** [comment]
@gunzip I changed my mind, I think

```ts
t.TypeOfProps<R> & t.TypeOfPartialProps<O>,
t.OutputOfProps<R> & t.OutputOfPartialProps<O>
```

is better (and more future proof, see https://github.com/gcanti/io-ts/issues/140)

**Comment by gunzip** [comment]
ahh nice ! this is our implementation by now:
https://github.com/teamdigitale/digital-citizenship-functions/blob/master/lib/utils/types.ts#L107

**Pull request merged**
