### PR TITLE
add taggedUnion

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by sledorze** [comment]
@gcanti looks good! Thanks :)

**Comment by gcanti** [comment]
```
union (good cart) x 1,960,862 ops/sec ±0.59% (87 runs sampled)
taggedUnion (good cart) x 1,189,883 ops/sec ±0.59% (88 runs sampled)
union (bad cart) x 312,810 ops/sec ±0.31% (86 runs sampled)
taggedUnion (bad cart) x 1,002,295 ops/sec ±0.32% (88 runs sampled)
union (good updatePrice) x 340,547 ops/sec ±0.24% (88 runs sampled)
taggedUnion (good updatePrice) x 887,113 ops/sec ±0.59% (88 runs sampled)
union (bad updatePrice) x 310,769 ops/sec ±0.38% (85 runs sampled)
taggedUnion (bad updatePrice) x 804,873 ops/sec ±0.32% (85 runs sampled)
```

So in the worst case is ~ 3X. With *only 4 elements*. In your case, where there are tenths of elements, I would expect a spectacular gain

**Comment by gcanti** [comment]
@sledorze any further comment before merging and releasing?

**Comment by sledorze** [comment]
@gcanti besides that I'm fine with a release; are you planning a '@next' ?

**Comment by gcanti** [comment]
> we should state in the doc what the pros/cons are compared to union

Sure, could you please suggest some wording?

> are you planning a '@next' ?

No, a regular release (0.9.7)

**Comment by gcanti** [comment]
> could you please suggest some wording?

@sledorze actually there no hurry for this, please send a PR when you find some time

**Pull request merged**
