### PR TITLE
Various optimizations

### PR DESCRIPTION
**Pull request by gcanti**
Using `./perf/index.js`

---

`concat(element)` (current implementation)

invalid payload x 200,425 ops/sec ±0.74% (89 runs sampled)
valid payload (no errors) x 181,576 ops/sec ±1.00% (87 runs sampled)

`concat([element])`

invalid payload x 258,902 ops/sec ±0.61% (89 runs sampled)
valid payload (no errors) x 227,362 ops/sec ±1.54% (86 runs sampled)

### CODE REVIEW

**Comment by gcanti** [comment]
@sledorze this looks a real gain though

**Comment by gcanti** [comment]
It's pretty surprising by the way, I'm doing something wrong?

This is another benchmark

```ts
var Benchmark = require('benchmark')

const suite = new Benchmark.Suite()

const x = [1, 2, 3]

suite
  .add('concat(a)', function() {
    x.concat(4)
  })
  .add('concat([a])', function() {
    x.concat([4])
  })
  .on('cycle', function(event) {
    console.log(String(event.target))
  })
  .on('complete', function() {
    console.log('Fastest is ' + this.filter('fastest').map('name'))
  })
  .run({ async: true })
```

Results

```
x.concat(4) // 2,935,475 ops/sec ±0.87% (82 runs sampled)
x.concat([4]) // 5,421,103 ops/sec ±0.93% (86 runs sampled)
```

**Comment by sledorze** [comment]
@gcanti that's crazy, maybe due to recent optimisations changes in V8.
I'm wondering if, as we decide to choose an implementation over another based on a comparison, if we should not enforce in a test that, so that if it ever change, we can adapt..

`x.concat([4])` must be faster than `x.concat(4)`

**Comment by gcanti** [comment]
> if we should not enforce in a test that, so that if it ever change, we can adapt..

That would be nice

**Pull request merged**
